.config/sway/config.d/50-openSUSE.conf

mako is started when needed via D-BUS activation. Not starting it
explicitly can improve Sway's startup time.
See https://github.com/emersion/mako/blob/237f6eabdd3e428cefc852a53306d34ef481c8a5/README.md#running
Related discussion: https://github.com/openSUSE/openSUSEway/issues/3#issuecomment-649524397

Don't start mako explicitly

---

README.md
greetd/config.toml
greetd/environments
greetd/sway-config
openSUSEway.sh
sway/sway-run.sh
sway/sway-session.target
sway/sway.desktop
sway/sway.service

This fixes #28 and fixes #27 .
Don't force environment, instead add it to the wrapper script.
Add greetd config files to install it later with openSUSEway pattern and package.

moving enviroments to run script, adding greetd config files

---

.config/sway/config.d/50-openSUSE.conf

Set the "allow-boost" flag to set the volume higher than 100%.
As wob currently only supports numbers up to 100, the value passed to wob is capped at 100 to avoid it breaking.
This capping may be removed in the future, if this feature https://github.com/francma/wob/issues/54 gets implemented.

Allow increasing volume over 100%

---

.config/sway/config.d/50-openSUSE.conf

Add requirement of `playerctl` package.
Or perhaps we can package and use https://github.com/mariusor/mpris-ctl
Actually there is now package at https://build.opensuse.org/package/show/home:mcepl:work/mpris-ctl

Add configuration for Play/Pause, Next, Prev multimedia keys.

---

.config/sway/config.d/50-openSUSE.conf

E.g., mpris-ctl from openSUSE package.

Allow users different MPRIS handler for multimedia keys.

---

.config/sway/config

So that an user can set different terminal application (or use different options for alacritty).

Use late evaluation of $term variable for bindsym $mod+Return

---

greetd/config.toml
greetd/sway-config

in case GDM is installed it creates `/usr/lib/systemd/logind.conf.d/reserveVT.conf` with `ReserveVT=1` which makes it unavailable for greeter.
fixes #52

GDM messes up tty1

---

.config/alacritty/alacritty.yml

Configuration option background_opacity is deprecated from version
0.10.0 and is replaced by window.opacity

Use new option for window opacity

---

.config/sway/config.d/50-openSUSE.conf

Add theme using wob command line options. Closes #47.
Upstream wob has moved to a .ini configuration file, but has not released the next version yet.
It will be easy to migrate this configuration to the wob.ini format once it is released.

Add openSUSE wob theme

---

.config/sway/config.d/50-openSUSE.conf
greetd/sway-config

Enable sensible touchpad behaviour by default, both in the sway session
and in greetd.
Cycle through workspaces with mod+tab, mod+shift+tab.
Address some suggestions from #69

Improve some defaults

---

sway/sway-run.sh

GDM and KDE Plasma source systemd user environment variables from ~/.config/environment.d/, sway does not [0].
Let's provide this functionality while we're at it.
[0] https://wiki.archlinux.org/title/Environment_variables#Wayland_environment

Import user configuration variables

---

sway/sway-run.sh

As mentioned in #77, I just realized this fix is needed to actually import all variables.

Import all user configuration variables from environment.d

---

.config/sway/config.d/50-openSUSE.conf
openSUSEway.spec

spec changes (diff from 0.14):
```
...
+Requires:       wl-clipboard
+Requires:       clipman
+Requires:       mpris-ctl
+Requires:       sway-marker
...
+Requires:       SwayNotificationCenter
...
+
+## wob
+install -D -p -m 644 .config/wob/wob.ini %{buildroot}%{_sysconfdir}/sway/wob/wob.ini
+
+## swaync
+install -D -p -m 644 .config/swaync/config.json %{buildroot}%{_sysconfdir}/sway/swaync/config.json
+install -D -p -m 644 .config/swaync/style.css %{buildroot}%{_sysconfdir}/sway/swaync/style.css
...
+%dir %{_sysconfdir}/sway/wob
+%config %{_sysconfdir}/sway/wob/wob.ini
+
+%dir %{_sysconfdir}/sway/swaync
+%config %{_sysconfdir}/sway/swaync/config.json
+%config %{_sysconfdir}/sway/swaync/style.css
+
...
```
so I added some packages as well as added configs for wob and swaync.
swaync now …

changes for 0.15

---

openSUSEway.spec

Both sway.service and sway-session.target are to be installed in the user systemd session.
Fix #95.

Install sway systemd components to the correct directories

---

sway/sway-run.sh

Based on https://forum.endeavouros.com/t/sway-with-nvidia-tutorial/23733, these have been the changes needed to make it work.

Allow sway to be run with proprietary drivers

---

.config/waybar/style.css

The default style uses some glyphs for the config (ie battery full) that are depending on the private use area of Unicode. The style defines only Source Sans Pro as a font which does not contain these glyphs, and instead displays Chinese glyphs.
This fixes part of this, but an SR making the waybar package depend on the fontawesome-font package is also needed.

Fix missing glyphs on the default style

---

.config/alacritty/alacritty.toml
.config/alacritty/alacritty.yml
.config/sway/config
openSUSEway.spec

YAML configuration is deprecated as of Alacritty version 0.13.0.
Resolve this banner for new users:
Users with a custom Alacritty/Sway configuration need to migrate and update on their own, I think it is not a good idea to call the migration in a post script as users might have more complex YAML configurations.
See https://github.com/alacritty/alacritty/issues/6592.

Migrate Alacritty configuration to TOML

---

.config/sway/config.d/50-openSUSE.conf
openSUSEway.spec

This is my screenshot configuration using `grim` and `slurp`. It allows to:
- `Print`: screenshot all outputs
- `$mod + Print`: screenshot the focused output
- `Shift + Print`: screenshot the focused window
- `Mod1 + Print`: screenshot an interactively selected window
- `Ctrl + Print`: screenshot an interactively selected area
Before I merge this PR, I want to open this to contributions if others have better configurations.

Add screenshot utility configuration

---

.config/sway/config.d/50-openSUSE.conf

This adds a screenshot mode menu instead of the individual screenshot options. The mode menu can be opened with `$mod+Print` and displays this text:
`Screenshot: (f) full, (s) select window, (a) select area, (w) focused window, (o) focused output [Ctrl+ saves to clipboard]`
The text is a bit long, and might not display fully in the bar depending on leftover space. Hovering over the menu text displays a tooltip with the full text, however.
The options should be quite intuitive.
- `f` takes a screenshot of all visible outputs
- `s` prompts the user to select a window and takes a screenshot of that
- `a` prompts the user to select a rectangular area and takes a screenshot of that
- `w` takes a screenshot of the window currently under focus
- `o` takes a screenshot of the output currently …

Add screenshot mode menu

---

.config/waybar/config
.config/waybar/style.css
openSUSEway.spec

This is my waybar bluetooth module I've had forever.
Features:
- color coded: neutral color when on but disconnected, greyed out when disabled, green (with number of connected devices) when connected
- tooltip shows controller address (not too useful but it's there), connection status, and number of connected devices if any
- left click toggles bluetooth on/off
- right click opens a terminal with bluetoothctl (could use some improvement on e.g. opening $TERM instead of fixed alacritty)

Add bluetooth waybar module

---

.config/sway/config.d/50-openSUSE.conf

Instead of $screenshot_focused_output_clipboard the variable $screenshot_focused_output was set two times

Screenshot_focused_output misses clipboard

---

.config/sway/config
.config/sway/config.d/50-openSUSE.conf

The idle configuration uses "output * dpms on/off" to switch off the monitors.
According to the man-page of sway-output "dpms" is an alias for "power" and depricated.
This change would make the configuration compliant with the current settings of sway and swayidle, which both use "power".
Since the configuration serves as a reference for many users, it makes sense to adapt this setting to the current recommendation.

Change "dpms" to "power"

---

.config/waybar/config

Change waybar workspace appearance from:
to
Fix #141

Change workspace indicator to number, keep logo only on active workspace

---

.config/sway/config.d/50-openSUSE.conf

Increase lock timer to 15 minutes. After one additional minute, turn screens off.
Fix #150.

Increase lock timer duration

---

.config/waybar/config

Replace Fontawesome SUSE logo (f7d6) with openSUSE (e62b)

---

.config/swaync/config.json

It looks like it works much better without it. Recently I got "Do something" notification, which is just an example.

Remove examples from NC config

---

.config/waybar/config

After initial install of openSUSEway waybar wasn't launching.So I decided to check what's up by running waybar from commandline and  got this error
```
[info]Using configuration file /etc/xdg/waybar/config 
[error]Error parsing JSON: * Line 35, Column 17
Bad escape sequence in string
See Line 35, Column 40 for detail
```
Double escaping the '+' in line 35 fixed the issue for me
``` js
"exec": "zypper lu | grep 'v \+|' | wc -l; echo 'packages to update'",
```

Fix JSON parsing issue that was preventing waybar from launching

---

.config/alacritty/alacritty.toml
.config/sway/config.d/50-openSUSE.conf
.config/swaylock/openSUSEway.conf
greetd/style.css

Use new openSUSE default dark background. Raise alacritty opacity to `0-75`, experimentally determined to look nice with the new background:
Fix #175

New background

---

openSUSEway.spec

fixes #178 
The fonts should be dependencies of the branding package itself, not the meta package.
This PR adds the used fonts of `waybar-branding-openSUSE` as requirements to it.
I did not dare to remove any fonts from the meta package but I am guessing that most of them should be specified in the branding packages.

waybar-branding-openSUSE: add fonts as dependencies

---

openSUSEway.spec

The dependency on `bash-completion` will obviously pull in the package, along with all the other completion packages such as `btrfsprogs-bash-completion` for packages installed on the system. Attempting to remove `bash-completion` will want to remove `openSUSEway` due to the hard dependency.
`bash-completion` isn't strictly required as `bash` isn't strictly required for `openSUSEway`, and so this dependency is annoying for those who want to use a different shell.
I believe `bash-completion` is installed by default on new installations, so in terms of "user friendliness" removing the dependency shouldn't change that experience.

Remove unused bsah-completion dependency

---

.config/waybar/style.css

Currently the workspaces have a 5px margin to the left and right.
This has been bugging me because this means that there are 5 pixels to the left of the workspaces where the first workspace cannot be clicked.
Buttons in corners should always be clickable from the entire corner, to support [Fitt's Law](https://en.wikipedia.org/wiki/Fitts's_law). Having a button in the corner essentially makes the button infinitely bug because you can click it no matter how far you move the cursor into the corner.
So that's why I removed that 5px margin, now you can slam your mouse into the corner and always be able to click on the first workspace.
I also removed the left margin on the scratchpad. Combined with the margin from the workspaces the margin between the workspaces and scratchpad would've been …

waybar style.css: make workspace and scratchpad have no left margins

---

.config/waybar/config.jsonc

Toggle pulseaudio module alt format (number) with middle click instead of right click, which would collide with the right-click action (opening `pavucontrol`).
Also enable the tooltip while we're at it.
Fixes #190

Improve waybar pulseaudio module configuration

---

.config/sway/config.d/50-openSUSE.conf

Add client `indicator` and `child_border` color for focused window, which previously only featured the three main required colors.
From `man 5 sway`:
```manpage
client.<class> <border> <background> <text> [<indicator> [<child_border>]]
Configures  the  color  of window borders and title bars. The first three colors are required.
When omitted indicator will use a sane default and child_border will use  the  color  set  for
background. Colors may be specified in hex, either as #RRGGBB or #RRGGBBAA.
...
indicator
The color used to indicate where a new view will open. In a tiled  container,  this  would
paint the right border of the current view if a new view would be opened to the right.
child_border
The border around the view itself.
```
I've picked our dull green color (`#6da741`) for the …

Add client indicator and child_border colors for focused window

---

openSUSEway.rpmlintrc
openSUSEway.spec

This needs to be tracked in Git as well, since the file needs to be mentioned as `Source` in the spec file.

Add openSUSEway.rpmlintrc

---

.config/waybar/config.jsonc

- Show network information in the tooltip
- Instead of clicking to see an alternative representation of the network  widget, show the network information in the tooltip.
- For a generic network show the interface name, IP address, and up/down bandwidth statistics.
- If the network is wifi, also show the essid, signal strength and wifi frequency.
- Right click the network widget to open nmtui

Improve network widget

---

openSUSEway.spec

I don't use NetworkManager on my machine, and openSUSEway works fine without it. Installing a network management solution should be part of a base system pattern and not part of the desktop environment.

Remove requirement for NetworkManager

---

.config/waybar/config.jsonc
openSUSEway.spec

This PR improves bluetooth handling in openSUSEway.
- Use `bluetuith` for interactive bluetooth management
`bluetuith` still requires `bluez`, so `bluetoothctl` (provided by `bluez`) remains available for non-interactive use.
- Use `bluetoothctl` to toggle bluetooth power in Waybar
The previously used `bluetooth` binary is provided by the `tlp` package, which is not a requirement of openSUSEway and is not (anymore?) installed by default on openSUSE Tumbleweed.
Fixes #163

Bluetooth improvements

---

.config/sway/config.d/50-openSUSE.conf
openSUSEway.spec

Volume boost was enabled in d19c2677790013fa35aff8d1a92b010c3855cb78 in #31, but back then `wob` was capped to showing a maximum value of 100. This limitation no longer holds, and our `wob` configuration already supports showing values over 100 as a red bar.

Allow volume to show over 100% in wob
